version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "${EXTERNAL_IP}:25:25"
    - "${EXTERNAL_IP}:143:143"
    - "${EXTERNAL_IP}:587:587"
    - "${EXTERNAL_IP}:993:993"
    volumes:
    - maillogs:/var/log/mail
    - /mnt/mail/maildata:/var/mail
    - /mnt/mail/mailstate:/var/mail-state
    - /mnt/mail/docker-mailserver/config/:/tmp/docker-mailserver/
    - ../letsencrypt/etc:/etc/letsencrypt/:ro
    env_file:
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maillogs:
    driver: local
